services:
  dev-backend:
    container_name: dev-backend
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    user: vscode
    environment:
      SPRING_PROFILES_ACTIVE: dev
    command: sleep infinity

  dev-frontend:
    container_name: dev-frontend
    image: "mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm"
    volumes:
      - .:/workspace
    ports:
      - "4173:4173"
    environment:
      - BACKEND_URL=http://dev-backend:8080
    command: sleep infinity