# Development properties
spring.datasource.url=jdbc:h2:mem:hotel_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true